export const AUTH = '/auth'
export const PEOPLE_AND_PROJECTS = '/people-and-projects'
export const AUTH_CONTINUE = '/auth-continue'
export const MY_BLOG = '/blog'
export const SUBSCRIPTIONS = '/subscriptions'